version: "3.9"

services:
  grafana:
    image: grafana/grafana:10.2.0
    container_name: "pcap-grafana"
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana:rw"

  mysql:
    image: mysql:8.0-debian
    container_name: "pcap-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: grafana
      MYSQL_PASSWORD: 1234
    volumes:
      - "${PWD}/data/mysql:/var/lib/mysql"
      - "${PWD}/mysql/config:/etc/my.cnf.d"

volumes:
  grafana: