{
 "title": "Pcap",
 "time": { "from": "2024-05-22T00:00:00.000Z", "to": "2024-05-23T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "seq",
    "label": "Seq",
    "query": "select seq from record group by seq;"
   },
   {
    "name": "needle",
    "query": "select data from record group by data"
   },
   {
    "name": "time_pr",
    "label": "Time Precision",
    "query": "ms : (UNIX_TIMESTAMP(`time`) DIV 1) + (MICROSECOND(`time`) DIV 1000) / 1000"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboad legend\n\nDataset range - `11:10 - 12:30` UTC\n\n`rate_in` - packages from intranet\n\n`rate_ex` - packages from extranet"
   },
   "targets": [
    { "dataset": "pcap" }
   ]
  },
  { "title": "TCP - $needle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "needle" },
  {
   "title": "Rate of $needle in ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_in`,\n    count(*) rate_in\nFROM record\nWHERE $__timeFilter(`time`) and data = $needle and src LIKE '10%'\nGROUP BY `time_ms_in`\nORDER BY `time_ms_in`;\n"
    },
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_ex`,\n    count(*) rate_ex\nFROM record\nWHERE $__timeFilter(`time`) and data = $needle and src NOT LIKE '10%'\nGROUP BY `time_ms_ex`\nORDER BY `time_ms_ex`;\n"
    }
   ]
  },
  {
   "title": "Rate of $needle at $seq seq",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_in`,\n    count(*) rate_in\nFROM record\nWHERE $__timeFilter(`time`) and data = $needle and seq = $seq and src LIKE '10%'\nGROUP BY `time_ms_in`\nORDER BY `time_ms_in`;\n\n\n"
    },
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_ex`,\n    count(*) rate_ex\nFROM record\nWHERE $__timeFilter(`time`) and data = $needle and seq = $seq and src NOT LIKE '10%'\nGROUP BY `time_ms_ex`\nORDER BY `time_ms_ex`;\n\n\n"
    }
   ]
  },
  {
   "title": "Rate of repeated TCP Retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_in`,\n    count(*) rate_in\nFROM record_grouped_rt\nWHERE $__timeFilter(`time`) and src LIKE '10%'\nGROUP BY `time_ms_in`\nORDER BY `time_ms_in`;\n"
    },
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_ex`,\n    count(*) rate_ex\nFROM record_grouped_rt\nWHERE $__timeFilter(`time`) and src NOT LIKE '10%'\nGROUP BY `time_ms_ex`\nORDER BY `time_ms_ex`;\n"
    }
   ]
  },
  {
   "title": "Rate of repeated TCP Retransmissions at $seq seq",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_in`,\n    count(*) rate_in\nFROM record_grouped_rt\nWHERE $__timeFilter(`time`) and seq = $seq and src LIKE '10%'\nGROUP BY `time_ms_in`\nORDER BY `time_ms_in`;\n"
    },
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n    $time_pr as `time`,\n    $time_pr AS `time_ms_ex`,\n    count(*) rate_ex\nFROM record_grouped_rt\nWHERE $__timeFilter(`time`) and seq = $seq and src NOT LIKE '10%'\nGROUP BY `time_ms_ex`\nORDER BY `time_ms_ex`;\n"
    }
   ]
  },
  {
   "title": "Seq TCP RT",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "select \n  seq,\n  count(*) \nfrom record\nWHERE $__timeFilter(`time`)\ngroup by seq\norder by count(*) desc limit 100;"
    }
   ]
  },
  {
   "title": "Packets records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "pcap",
     "rawSql": "SELECT\n  `time`,\n  file,\n  `rel-id`\nFROM record\nWHERE $__timeFilter(`time`)\nORDER BY `time`"
    }
   ]
  }
 ]
}